"""
Readiness Check Registry.
Contains all 120+ check definitions organized by category.
Each definition describes what is checked, who owns it, and how to remediate it.
"""
from __future__ import annotations

from typing import Any


def _check(
    check_id: str,
    category: str,
    title: str,
    description: str,
    check_type: str,
    severity: str,
    automated: bool,
    manual_evidence_required: bool,
    recommended_evidence: str,
    remediation: str,
    owner: str,
) -> dict[str, Any]:
    return {
        "check_id": check_id,
        "category": category,
        "title": title,
        "description": description,
        "check_type": check_type,
        "severity": severity,
        "automated": automated,
        "manual_evidence_required": manual_evidence_required,
        "recommended_evidence": recommended_evidence,
        "remediation": remediation,
        "owner": owner,
    }


READINESS_CHECKS: list[dict[str, Any]] = [
    # -------------------------------------------------------------------------
    # A. ARCHITECTURE
    # -------------------------------------------------------------------------
    _check("ARCH-001", "ARCHITECTURE", "High-level architecture documented",
           "A high-level architecture document exists describing the system components.",
           "MANUAL", "MEDIUM", False, True,
           "Architecture diagram or README architecture section.",
           "Create docs/architecture.md with component diagram.", "Solution Architect"),
    _check("ARCH-002", "ARCHITECTURE", "Component boundaries are defined",
           "Frontend, backend, agent layer, RAG, and infra boundaries are documented.",
           "HYBRID", "MEDIUM", True, True,
           "Folder structure showing component separation.",
           "Document component boundaries in architecture docs.", "Solution Architect"),
    _check("ARCH-003", "ARCHITECTURE", "Frontend, backend, agents, RAG, infra folders exist",
           "Project contains frontend/, backend/, agents/, rag/, infra/ directories.",
           "AUTOMATED", "HIGH", True, False,
           "Folder existence confirmed by static check.",
           "Create missing top-level folders.", "Solution Architect"),
    _check("ARCH-004", "ARCHITECTURE", "Azure service mapping documented",
           "Azure services used by the platform are listed and mapped to components.",
           "MANUAL", "MEDIUM", False, True,
           "Azure service inventory document.",
           "Add Azure service mapping to architecture docs.", "Solution Architect"),
    _check("ARCH-005", "ARCHITECTURE", "Local and production modes are separated",
           "Config supports both local/dev mode and production Azure mode.",
           "AUTOMATED", "HIGH", True, False,
           "config.py has ai_provider, auth_mode, observability_mode settings.",
           "Implement mode separation via environment variables.", "Solution Architect"),

    # -------------------------------------------------------------------------
    # B. SECURITY
    # -------------------------------------------------------------------------
    _check("SEC-001", "SECURITY", "No secrets committed to repository",
           "Repository must not contain API keys, tokens, passwords, or connection strings.",
           "AUTOMATED", "BLOCKER", True, False,
           "No-secrets scan output showing no patterns found.",
           "Move secrets to Key Vault or secure pipeline variables.", "Security Team"),
    _check("SEC-002", "SECURITY", "Secret redaction utility exists",
           "A utility exists to redact secrets from logs and outputs.",
           "AUTOMATED", "HIGH", True, False,
           "backend/app/utils/secret_redactor.py or similar exists.",
           "Create secret redaction utility in utils/.", "Security Team"),
    _check("SEC-003", "SECURITY", "Security health endpoint exists",
           "A /api/v1/security/health or equivalent endpoint exists.",
           "AUTOMATED", "HIGH", True, False,
           "security_routes.py exists with health check.",
           "Add security health endpoint.", "Security Team"),
    _check("SEC-004", "SECURITY", "Admin APIs do not expose secrets",
           "Admin and config endpoints return no secrets, keys, or tokens.",
           "HYBRID", "BLOCKER", True, True,
           "Code review confirming no secret values in responses.",
           "Audit all admin endpoints for secret leakage.", "Security Team"),
    _check("SEC-005", "SECURITY", "Frontend does not expose backend secrets",
           "Frontend environment variables do not contain backend secrets.",
           "AUTOMATED", "BLOCKER", True, False,
           "frontend/.env.example has no real secrets.",
           "Move all secrets out of frontend env files.", "Security Team"),
    _check("SEC-006", "SECURITY", "Security runbooks exist",
           "Security incident runbooks are documented.",
           "AUTOMATED", "MEDIUM", True, False,
           "docs/runbooks/ contains security runbook files.",
           "Create security runbooks in docs/runbooks/.", "Security Team"),

    # -------------------------------------------------------------------------
    # C. IDENTITY AND ACCESS
    # -------------------------------------------------------------------------
    _check("IAM-001", "IDENTITY_AND_ACCESS", "Entra ID authentication structure exists",
           "Auth module supports Entra ID (MSAL/OIDC) in production mode.",
           "AUTOMATED", "BLOCKER", True, False,
           "backend/app/auth/ folder with entra_id provider exists.",
           "Implement Entra ID auth provider.", "Identity Team"),
    _check("IAM-002", "IDENTITY_AND_ACCESS", "Local auth mode exists for development",
           "A local/demo auth mode allows development without Azure AD.",
           "AUTOMATED", "HIGH", True, False,
           "config.py has auth_mode setting; local auth handler exists.",
           "Implement local auth mode fallback.", "Identity Team"),
    _check("IAM-003", "IDENTITY_AND_ACCESS", "Backend role-based permissions are enforced",
           "All backend routes enforce role-based access control.",
           "AUTOMATED", "BLOCKER", True, False,
           "permissions.py with PERMISSIONS_BY_ROLE dict exists.",
           "Implement RBAC in all route handlers.", "Identity Team"),
    _check("IAM-004", "IDENTITY_AND_ACCESS", "Auditor role is read-only",
           "AUDITOR role cannot write, update, or delete data.",
           "AUTOMATED", "HIGH", True, False,
           "AUDITOR permissions in permissions.py contain only VIEW_ permissions.",
           "Restrict AUDITOR permissions to VIEW_ only.", "Identity Team"),
    _check("IAM-005", "IDENTITY_AND_ACCESS", "Admin-only endpoints are protected",
           "Routes requiring ADMIN role check permissions correctly.",
           "AUTOMATED", "BLOCKER", True, False,
           "require_permission(Permission.ADMIN_CONFIG) used in admin routes.",
           "Add require_permission guards to all admin routes.", "Identity Team"),
    _check("IAM-006", "IDENTITY_AND_ACCESS", "Auth route documentation exists",
           "Authentication flows are documented for operators.",
           "AUTOMATED", "LOW", True, False,
           "docs/entra-id-authentication.md exists.",
           "Create Entra ID auth documentation.", "Identity Team"),

    # -------------------------------------------------------------------------
    # D. SECRETS AND KEY MANAGEMENT
    # -------------------------------------------------------------------------
    _check("KEY-001", "SECRETS_AND_KEY_MANAGEMENT", "Key Vault provider exists",
           "A Key Vault secret provider is implemented for production mode.",
           "AUTOMATED", "HIGH", True, False,
           "backend/app/security/key_vault_provider.py or secure_config_loader.py exists.",
           "Implement Key Vault provider in security module.", "Platform Team"),
    _check("KEY-002", "SECRETS_AND_KEY_MANAGEMENT", "Environment provider exists for local mode",
           "Local mode reads secrets from environment variables, not hardcoded.",
           "AUTOMATED", "HIGH", True, False,
           "secure_config_loader.py reads from os.environ.",
           "Implement environment variable provider.", "Platform Team"),
    _check("KEY-003", "SECRETS_AND_KEY_MANAGEMENT", "Managed identity support exists",
           "Platform supports Azure Managed Identity for credential-free auth.",
           "AUTOMATED", "HIGH", True, False,
           "config.py has use_managed_identity flag.",
           "Add managed identity support to auth/secret loader.", "Platform Team"),
    _check("KEY-004", "SECRETS_AND_KEY_MANAGEMENT", "Key Vault Bicep module exists",
           "Infrastructure includes a Key Vault Bicep template.",
           "AUTOMATED", "MEDIUM", True, False,
           "infra/bicep/ contains key-vault.bicep or similar.",
           "Create Key Vault Bicep module in infra/bicep/.", "Platform Team"),
    _check("KEY-005", "SECRETS_AND_KEY_MANAGEMENT", "Secret values not returned in health/admin APIs",
           "Health and admin APIs return no raw secret values.",
           "HYBRID", "BLOCKER", True, True,
           "Code review confirming safe_summary() hides secrets.",
           "Audit all health/admin API responses for secret exposure.", "Security Team"),
    _check("KEY-006", "SECRETS_AND_KEY_MANAGEMENT", "No secrets in Bicep parameter files",
           "Bicep parameter files contain no real secret values.",
           "AUTOMATED", "BLOCKER", True, False,
           "infra/bicep/parameters/ files have no hardcoded secrets.",
           "Use Key Vault references in Bicep parameter files.", "Security Team"),

    # -------------------------------------------------------------------------
    # E. NETWORKING
    # -------------------------------------------------------------------------
    _check("NET-001", "NETWORKING", "Private endpoint Bicep module exists",
           "Infra includes private endpoint configuration for Azure services.",
           "AUTOMATED", "HIGH", True, False,
           "infra/bicep/ contains private-endpoint.bicep or networking module.",
           "Create private endpoint Bicep module.", "Platform Team"),
    _check("NET-002", "NETWORKING", "Private DNS zone module exists",
           "Infra includes private DNS zone configuration.",
           "AUTOMATED", "HIGH", True, False,
           "infra/bicep/ contains private-dns or networking configuration.",
           "Create private DNS zone Bicep module.", "Platform Team"),
    _check("NET-003", "NETWORKING", "Public network access flags exist",
           "Config supports disabling public network access on Azure resources.",
           "AUTOMATED", "HIGH", True, False,
           "config.py has disable_public_network_access flag.",
           "Add public network access control flags to config.", "Platform Team"),
    _check("NET-004", "NETWORKING", "Container Apps VNet integration documented",
           "Container Apps VNet integration is documented for production deployment.",
           "MANUAL", "MEDIUM", False, True,
           "Architecture docs reference VNet integration.",
           "Document VNet integration in deployment hardening docs.", "Platform Team"),
    _check("NET-005", "NETWORKING", "Network hardening documentation exists",
           "A network hardening guide exists for production deployment.",
           "AUTOMATED", "MEDIUM", True, False,
           "docs/deployment-hardening-key-vault-private-endpoints-managed-identity.md exists.",
           "Create network hardening documentation.", "Platform Team"),

    # -------------------------------------------------------------------------
    # F. AI SAFETY AND GUARDRAILS
    # -------------------------------------------------------------------------
    _check("AI-001", "AI_SAFETY_AND_GUARDRAILS", "Human review is always required",
           "System config enforces human review before any consequential decision.",
           "AUTOMATED", "BLOCKER", True, False,
           "config.py ai_safety_require_human_review=True.",
           "Set ai_safety_require_human_review=True in all environments.", "AI Governance Team"),
    _check("AI-002", "AI_SAFETY_AND_GUARDRAILS", "Guardrail engine exists",
           "A guardrail engine validates AI outputs before they reach human reviewers.",
           "AUTOMATED", "HIGH", True, False,
           "backend/app/security/guardrail_engine.py or similar exists.",
           "Implement guardrail engine in security module.", "AI Governance Team"),
    _check("AI-003", "AI_SAFETY_AND_GUARDRAILS", "PII redaction before LLM calls exists",
           "PII is redacted from transaction data before sending to LLM.",
           "AUTOMATED", "BLOCKER", True, False,
           "pii_redactor.py or similar exists in utils/ or security/.",
           "Implement PII redaction utility and use it before LLM calls.", "AI Governance Team"),
    _check("AI-004", "AI_SAFETY_AND_GUARDRAILS", "Prompt injection detector exists",
           "System detects and blocks prompt injection attempts.",
           "AUTOMATED", "HIGH", True, False,
           "prompt_injection_detector.py exists in security/.",
           "Implement prompt injection detector.", "AI Governance Team"),
    _check("AI-005", "AI_SAFETY_AND_GUARDRAILS", "Output validator exists",
           "AI output is validated for structure and safety before use.",
           "AUTOMATED", "HIGH", True, False,
           "output_validator.py or llm_output_validator.py exists.",
           "Implement AI output validator.", "AI Governance Team"),
    _check("AI-006", "AI_SAFETY_AND_GUARDRAILS", "Direct fraud accusation language is blocked",
           "AI system cannot directly accuse a customer of fraud in output.",
           "HYBRID", "BLOCKER", True, True,
           "Guardrail tests confirming accusation language is blocked.",
           "Add accusation language filter to guardrail engine.", "AI Governance Team"),
    _check("AI-007", "AI_SAFETY_AND_GUARDRAILS", "LLM output JSON validation exists",
           "LLM responses are validated as valid JSON before processing.",
           "AUTOMATED", "HIGH", True, False,
           "JSON validation logic in agent or LLM client code.",
           "Add JSON schema validation to LLM response handling.", "AI Governance Team"),
    _check("AI-008", "AI_SAFETY_AND_GUARDRAILS", "Fallback mode exists when LLM fails",
           "System gracefully handles LLM failures with a local fallback.",
           "AUTOMATED", "HIGH", True, False,
           "config.py ai_provider_allow_fallback=True; fallback agent logic exists.",
           "Implement LLM fallback mode in agent layer.", "AI Governance Team"),

    # -------------------------------------------------------------------------
    # G. RAG AND KNOWLEDGE GROUNDING
    # -------------------------------------------------------------------------
    _check("RAG-001", "RAG_AND_KNOWLEDGE_GROUNDING", "Azure AI Search retriever exists",
           "A retriever for Azure AI Search is implemented (may be disabled in MVP).",
           "AUTOMATED", "HIGH", True, False,
           "rag/ folder contains azure_search_retriever.py or similar.",
           "Implement Azure AI Search retriever.", "Platform Team"),
    _check("RAG-002", "RAG_AND_KNOWLEDGE_GROUNDING", "Local fallback retriever exists",
           "A local keyword retriever works without Azure AI Search.",
           "AUTOMATED", "HIGH", True, False,
           "rag/ folder contains local_retriever.py or similar.",
           "Implement local fallback retriever.", "Platform Team"),
    _check("RAG-003", "RAG_AND_KNOWLEDGE_GROUNDING", "Policy index schema exists",
           "Policy document index schema is defined for RAG retrieval.",
           "AUTOMATED", "MEDIUM", True, False,
           "rag/ folder contains policy index schema or config.",
           "Define policy index schema in RAG module.", "Platform Team"),
    _check("RAG-004", "RAG_AND_KNOWLEDGE_GROUNDING", "Historical case index schema exists",
           "Historical case index schema is defined for RAG retrieval.",
           "AUTOMATED", "MEDIUM", True, False,
           "rag/ folder contains historical case index schema.",
           "Define historical case index schema in RAG module.", "Platform Team"),
    _check("RAG-005", "RAG_AND_KNOWLEDGE_GROUNDING", "Citation builder exists",
           "A citation builder constructs grounded citations from RAG results.",
           "AUTOMATED", "HIGH", True, False,
           "rag/ folder contains citation_builder.py or similar.",
           "Implement citation builder in RAG module.", "Platform Team"),
    _check("RAG-006", "RAG_AND_KNOWLEDGE_GROUNDING", "Citation validator exists",
           "Retrieved citations are validated for relevance before inclusion.",
           "AUTOMATED", "HIGH", True, False,
           "rag/ folder contains citation_validator.py or similar.",
           "Implement citation validator in RAG module.", "Platform Team"),
    _check("RAG-007", "RAG_AND_KNOWLEDGE_GROUNDING", "RAG evaluation dataset exists",
           "An evaluation dataset exists to measure RAG retrieval quality.",
           "AUTOMATED", "MEDIUM", True, False,
           "tests/ or data/ folder contains RAG eval dataset.",
           "Create RAG evaluation dataset.", "Platform Team"),
    _check("RAG-008", "RAG_AND_KNOWLEDGE_GROUNDING", "RAG retrieval audit/telemetry exists",
           "RAG retrievals are logged and tracked via telemetry.",
           "AUTOMATED", "MEDIUM", True, False,
           "telemetry_events.py contains RAG_RETRIEVAL events.",
           "Add RAG telemetry events to telemetry_events.py.", "Platform Team"),

    # -------------------------------------------------------------------------
    # H. HUMAN IN THE LOOP
    # -------------------------------------------------------------------------
    _check("HITL-001", "HUMAN_IN_THE_LOOP", "Human review workflow exists",
           "A complete human review workflow is implemented.",
           "AUTOMATED", "BLOCKER", True, False,
           "backend/app/services/human_review_service.py exists.",
           "Implement human review service.", "Fraud Operations Team"),
    _check("HITL-002", "HUMAN_IN_THE_LOOP", "Role-based review permissions exist",
           "Only authorized roles can submit human reviews.",
           "AUTOMATED", "BLOCKER", True, False,
           "permissions.py has SUBMIT_HUMAN_REVIEW permission.",
           "Add SUBMIT_HUMAN_REVIEW permission guard to review endpoints.", "Fraud Operations Team"),
    _check("HITL-003", "HUMAN_IN_THE_LOOP", "Evidence acknowledgement required",
           "Reviewers must acknowledge evidence before submitting a decision.",
           "HYBRID", "HIGH", True, True,
           "Review schema includes evidence_acknowledged field.",
           "Add evidence acknowledgement requirement to review workflow.", "Fraud Operations Team"),
    _check("HITL-004", "HUMAN_IN_THE_LOOP", "Policy acknowledgement required",
           "Reviewers must acknowledge relevant policy before deciding.",
           "HYBRID", "HIGH", True, True,
           "Review schema includes policy_acknowledged field.",
           "Add policy acknowledgement to review workflow.", "Fraud Operations Team"),
    _check("HITL-005", "HUMAN_IN_THE_LOOP", "Human override tracking exists",
           "Cases where humans override AI recommendations are tracked.",
           "AUTOMATED", "HIGH", True, False,
           "backend/app/services/human_override_service.py exists.",
           "Implement human override tracking service.", "Fraud Operations Team"),
    _check("HITL-006", "HUMAN_IN_THE_LOOP", "Case status lifecycle exists",
           "Case status transitions are controlled and validated.",
           "AUTOMATED", "HIGH", True, False,
           "constants.py ALLOWED_STATUS_TRANSITIONS dict exists.",
           "Define and enforce case status lifecycle.", "Fraud Operations Team"),
    _check("HITL-007", "HUMAN_IN_THE_LOOP", "Closed cases are terminal",
           "Closed cases cannot be re-opened or modified.",
           "AUTOMATED", "HIGH", True, False,
           "ALLOWED_STATUS_TRANSITIONS[CLOSED] is empty set.",
           "Enforce terminal CLOSED status in status transition logic.", "Fraud Operations Team"),

    # -------------------------------------------------------------------------
    # I. AUDIT AND COMPLIANCE
    # -------------------------------------------------------------------------
    _check("AUD-001", "AUDIT_AND_COMPLIANCE", "Structured audit service exists",
           "An audit service records all system events in structured format.",
           "AUTOMATED", "BLOCKER", True, False,
           "backend/app/services/audit_service.py exists.",
           "Implement structured audit service.", "Compliance Team"),
    _check("AUD-002", "AUDIT_AND_COMPLIANCE", "Audit events stored locally for MVP",
           "Audit events are persisted in a local JSON store for MVP.",
           "AUTOMATED", "HIGH", True, False,
           "data/synthetic/audit_events.json exists or audit repository exists.",
           "Implement local audit event storage.", "Compliance Team"),
    _check("AUD-003", "AUDIT_AND_COMPLIANCE", "Audit metadata sanitizer exists",
           "Audit metadata is sanitized to remove PII and secrets before storage.",
           "AUTOMATED", "HIGH", True, False,
           "backend/app/utils/audit_sanitizer.py exists.",
           "Implement audit metadata sanitizer.", "Compliance Team"),
    _check("AUD-004", "AUDIT_AND_COMPLIANCE", "Human decisions are audited",
           "All human review decisions are recorded in the audit trail.",
           "AUTOMATED", "BLOCKER", True, False,
           "audit_service.create_human_decision_event() is called in review flow.",
           "Add audit calls to human review submission.", "Compliance Team"),
    _check("AUD-005", "AUDIT_AND_COMPLIANCE", "AI investigation events are audited",
           "AI investigation start and completion are recorded in audit trail.",
           "AUTOMATED", "HIGH", True, False,
           "audit_service.create_ai_investigation_event() is called.",
           "Add audit calls to investigation service.", "Compliance Team"),
    _check("AUD-006", "AUDIT_AND_COMPLIANCE", "Admin config changes are audited",
           "Admin configuration changes are recorded in the audit trail.",
           "AUTOMATED", "HIGH", True, False,
           "ADMIN_CONFIG_UPDATED audit events are emitted on config changes.",
           "Add audit calls to admin config update endpoints.", "Compliance Team"),
    _check("AUD-007", "AUDIT_AND_COMPLIANCE", "Compliance export exists",
           "A compliance export mechanism exists for regulatory reporting.",
           "AUTOMATED", "HIGH", True, False,
           "backend/app/compliance/ module exists.",
           "Implement compliance export service.", "Compliance Team"),

    # -------------------------------------------------------------------------
    # J. DATA RETENTION
    # -------------------------------------------------------------------------
    _check("RET-001", "DATA_RETENTION", "Data category enum exists",
           "DataCategory enum defines all data types subject to retention policy.",
           "AUTOMATED", "HIGH", True, False,
           "constants.py DataCategory enum exists.",
           "Define DataCategory enum in constants.py.", "Compliance Team"),
    _check("RET-002", "DATA_RETENTION", "Retention policy registry exists",
           "Retention policies are defined per data category.",
           "AUTOMATED", "HIGH", True, False,
           "data/synthetic/retention_policies.json or retention service exists.",
           "Implement retention policy registry.", "Compliance Team"),
    _check("RET-003", "DATA_RETENTION", "Legal hold service exists",
           "A legal hold service prevents premature deletion of case data.",
           "AUTOMATED", "HIGH", True, False,
           "backend/app/compliance/ or similar contains legal hold service.",
           "Implement legal hold service.", "Compliance Team"),
    _check("RET-004", "DATA_RETENTION", "Purge defaults to dry-run",
           "Data purge operations default to dry-run mode to prevent accidental deletion.",
           "AUTOMATED", "HIGH", True, False,
           "config.py purge_dry_run_default=True.",
           "Set purge_dry_run_default=True in config.", "Compliance Team"),
    _check("RET-005", "DATA_RETENTION", "Legal hold blocks purge",
           "Data under legal hold cannot be purged.",
           "AUTOMATED", "BLOCKER", True, False,
           "Purge service checks legal hold status before deleting.",
           "Add legal hold check to purge service.", "Compliance Team"),
    _check("RET-006", "DATA_RETENTION", "Compliance export redaction exists",
           "Compliance exports redact PII where required.",
           "AUTOMATED", "HIGH", True, False,
           "config.py compliance_export_redact_pii=True.",
           "Enable PII redaction in compliance export.", "Compliance Team"),
    _check("RET-007", "DATA_RETENTION", "Retention documentation exists",
           "Data retention policies are documented for compliance teams.",
           "AUTOMATED", "MEDIUM", True, False,
           "docs/data-retention-compliance-policy.md exists.",
           "Create data retention policy documentation.", "Compliance Team"),

    # -------------------------------------------------------------------------
    # K. OBSERVABILITY
    # -------------------------------------------------------------------------
    _check("OBS-001", "OBSERVABILITY", "Correlation ID middleware exists",
           "All API requests receive a correlation ID for end-to-end tracing.",
           "AUTOMATED", "HIGH", True, False,
           "observability/correlation.py exists.",
           "Implement correlation ID middleware.", "Platform Team"),
    _check("OBS-002", "OBSERVABILITY", "API telemetry middleware exists",
           "All API requests/responses are tracked via telemetry.",
           "AUTOMATED", "HIGH", True, False,
           "observability/middleware.py exists.",
           "Implement API telemetry middleware.", "Platform Team"),
    _check("OBS-003", "OBSERVABILITY", "Agent telemetry exists",
           "Agent execution events are tracked via telemetry.",
           "AUTOMATED", "HIGH", True, False,
           "telemetry_events.py contains AGENT_EXECUTION events.",
           "Add agent telemetry events.", "Platform Team"),
    _check("OBS-004", "OBSERVABILITY", "RAG telemetry exists",
           "RAG retrieval events are tracked via telemetry.",
           "AUTOMATED", "HIGH", True, False,
           "telemetry_events.py contains RAG_RETRIEVAL events.",
           "Add RAG telemetry events.", "Platform Team"),
    _check("OBS-005", "OBSERVABILITY", "LLM telemetry exists",
           "LLM call events including latency and token usage are tracked.",
           "AUTOMATED", "HIGH", True, False,
           "telemetry_events.py contains LLM_CALL events.",
           "Add LLM telemetry events.", "Platform Team"),
    _check("OBS-006", "OBSERVABILITY", "Application Insights config supported",
           "Application Insights connection string can be configured for production.",
           "AUTOMATED", "HIGH", True, False,
           "config.py has applicationinsights_connection_string field.",
           "Add Application Insights config support.", "Platform Team"),
    _check("OBS-007", "OBSERVABILITY", "KQL queries exist",
           "KQL query files exist for monitoring and alerting in production.",
           "AUTOMATED", "MEDIUM", True, False,
           "monitoring/kql/ folder contains .kql files.",
           "Create KQL queries for key metrics.", "Platform Team"),
    _check("OBS-008", "OBSERVABILITY", "Observability dashboard exists",
           "An observability dashboard UI exists for platform operators.",
           "AUTOMATED", "MEDIUM", True, False,
           "frontend/src/app/observability/ folder exists.",
           "Implement observability dashboard in frontend.", "Platform Team"),

    # -------------------------------------------------------------------------
    # L. ALERTING AND INCIDENT RESPONSE
    # -------------------------------------------------------------------------
    _check("ALERT-001", "ALERTING_AND_INCIDENT_RESPONSE", "Alert severity enum exists",
           "AlertSeverity enum defines severity levels for platform alerts.",
           "AUTOMATED", "HIGH", True, False,
           "constants.py AlertSeverity enum exists.",
           "Define AlertSeverity enum in constants.", "Platform Team"),
    _check("ALERT-002", "ALERTING_AND_INCIDENT_RESPONSE", "Alert evaluator exists",
           "An alert evaluation engine triggers alerts based on thresholds.",
           "AUTOMATED", "HIGH", True, False,
           "backend/app/alerting/ module exists.",
           "Implement alert evaluator.", "Platform Team"),
    _check("ALERT-003", "ALERTING_AND_INCIDENT_RESPONSE", "Incident lifecycle exists",
           "Incidents can be created, tracked, and resolved through a defined lifecycle.",
           "AUTOMATED", "HIGH", True, False,
           "IncidentStatus enum and incident routes exist.",
           "Implement incident lifecycle management.", "Platform Team"),
    _check("ALERT-004", "ALERTING_AND_INCIDENT_RESPONSE", "Runbooks exist",
           "Operational runbooks exist for common incidents.",
           "AUTOMATED", "HIGH", True, False,
           "docs/runbooks/ folder contains runbook .md files.",
           "Create runbooks for key alert types.", "Platform Team"),
    _check("ALERT-005", "ALERTING_AND_INCIDENT_RESPONSE", "Local alert simulation exists",
           "Alerts can be simulated locally for testing without Azure Monitor.",
           "AUTOMATED", "MEDIUM", True, False,
           "data/synthetic/alerts.json and alerting service exist.",
           "Implement local alert simulation.", "Platform Team"),
    _check("ALERT-006", "ALERTING_AND_INCIDENT_RESPONSE", "Alert/incident frontend dashboard exists",
           "Frontend dashboard for viewing alerts and incidents exists.",
           "AUTOMATED", "MEDIUM", True, False,
           "frontend/src/app/alerts/ and frontend/src/app/incidents/ exist.",
           "Implement alert and incident frontend pages.", "Platform Team"),
    _check("ALERT-007", "ALERTING_AND_INCIDENT_RESPONSE", "Notification integration exists or placeholder exists",
           "Notification system for alerts is implemented or has a placeholder.",
           "AUTOMATED", "MEDIUM", True, False,
           "notifications module or placeholder exists.",
           "Implement notification integration for alerts.", "Platform Team"),

    # -------------------------------------------------------------------------
    # M. RELIABILITY AND RESILIENCE
    # -------------------------------------------------------------------------
    _check("REL-001", "RELIABILITY_AND_RESILIENCE", "Retry logic exists for LLM calls",
           "LLM API calls include retry logic for transient failures.",
           "AUTOMATED", "HIGH", True, False,
           "config.py azure_openai_max_retries field exists.",
           "Implement retry logic in LLM client.", "Platform Team"),
    _check("REL-002", "RELIABILITY_AND_RESILIENCE", "Timeout handling exists",
           "LLM and external API calls have configurable timeouts.",
           "AUTOMATED", "HIGH", True, False,
           "config.py azure_openai_request_timeout_seconds field exists.",
           "Add timeout configuration to all external API calls.", "Platform Team"),
    _check("REL-003", "RELIABILITY_AND_RESILIENCE", "Fallback mode exists",
           "System operates in degraded mode when Azure services are unavailable.",
           "AUTOMATED", "HIGH", True, False,
           "config.py ai_provider_allow_fallback=True.",
           "Implement fallback mode for all Azure-dependent features.", "Platform Team"),
    _check("REL-004", "RELIABILITY_AND_RESILIENCE", "Circuit breaker or placeholder exists",
           "Circuit breaker pattern is implemented or documented for future use.",
           "MANUAL", "MEDIUM", False, True,
           "Circuit breaker implementation or documented design.",
           "Implement circuit breaker or document as future improvement.", "Platform Team"),
    _check("REL-005", "RELIABILITY_AND_RESILIENCE", "Failed agent execution handled safely",
           "Agent execution failures do not crash the API or corrupt case state.",
           "AUTOMATED", "HIGH", True, False,
           "Agent execution wrapped in try/except with error audit event.",
           "Add error handling to all agent execution paths.", "Platform Team"),
    _check("REL-006", "RELIABILITY_AND_RESILIENCE", "Investigation failure does not corrupt case state",
           "If investigation fails, case remains in a valid state.",
           "AUTOMATED", "HIGH", True, False,
           "Investigation service handles failures without corrupting case.",
           "Add safe error recovery to investigation service.", "Platform Team"),
    _check("REL-007", "RELIABILITY_AND_RESILIENCE", "Dead-letter queue placeholder/documentation exists",
           "Dead-letter queue for failed async operations is documented or implemented.",
           "MANUAL", "LOW", False, True,
           "Architecture docs or placeholder for dead-letter queue.",
           "Document dead-letter queue approach for production.", "Platform Team"),

    # -------------------------------------------------------------------------
    # N. PERFORMANCE AND SCALABILITY
    # -------------------------------------------------------------------------
    _check("PERF-001", "PERFORMANCE_AND_SCALABILITY", "Agent latency telemetry exists",
           "Agent execution latency is captured and reported via telemetry.",
           "AUTOMATED", "MEDIUM", True, False,
           "Agent telemetry includes duration_ms measurement.",
           "Add latency tracking to agent telemetry.", "Platform Team"),
    _check("PERF-002", "PERFORMANCE_AND_SCALABILITY", "RAG latency telemetry exists",
           "RAG retrieval latency is captured and reported.",
           "AUTOMATED", "MEDIUM", True, False,
           "RAG telemetry includes duration_ms measurement.",
           "Add latency tracking to RAG telemetry.", "Platform Team"),
    _check("PERF-003", "PERFORMANCE_AND_SCALABILITY", "LLM latency telemetry exists",
           "LLM call latency is captured and reported.",
           "AUTOMATED", "MEDIUM", True, False,
           "LLM telemetry includes latency_ms measurement.",
           "Add latency tracking to LLM telemetry.", "Platform Team"),
    _check("PERF-004", "PERFORMANCE_AND_SCALABILITY", "Container scaling settings exist in Bicep",
           "Container Apps Bicep templates include scaling configuration.",
           "AUTOMATED", "MEDIUM", True, False,
           "infra/bicep/ contains container-apps.bicep with scaling settings.",
           "Add scaling configuration to Container Apps Bicep template.", "Platform Team"),
    _check("PERF-005", "PERFORMANCE_AND_SCALABILITY", "Load/performance test placeholders exist",
           "Performance test scripts or placeholders exist.",
           "MANUAL", "LOW", False, True,
           "tests/performance/ folder or documented plan.",
           "Create performance test scripts or documented plan.", "Platform Team"),
    _check("PERF-006", "PERFORMANCE_AND_SCALABILITY", "Top expensive/slow cases visible",
           "Cost dashboard shows highest-cost or slowest cases.",
           "AUTOMATED", "LOW", True, False,
           "frontend/src/app/cost/ has case-level cost breakdown.",
           "Add case-level cost ranking to cost dashboard.", "Platform Team"),

    # -------------------------------------------------------------------------
    # O. COST MANAGEMENT
    # -------------------------------------------------------------------------
    _check("COST-001", "COST_MANAGEMENT", "Token usage capture exists",
           "Token usage (input/output) is captured for all LLM calls.",
           "AUTOMATED", "HIGH", True, False,
           "cost/ module or token_usage tracking in telemetry exists.",
           "Implement token usage capture in LLM client.", "Platform Team"),
    _check("COST-002", "COST_MANAGEMENT", "Cost estimator exists",
           "A cost estimator calculates cost from token usage.",
           "AUTOMATED", "HIGH", True, False,
           "backend/app/cost/ module exists with cost estimation.",
           "Implement cost estimator service.", "Platform Team"),
    _check("COST-003", "COST_MANAGEMENT", "Cost dashboard exists",
           "Frontend cost monitoring dashboard exists.",
           "AUTOMATED", "MEDIUM", True, False,
           "frontend/src/app/cost/ folder exists.",
           "Implement cost monitoring dashboard in frontend.", "Platform Team"),
    _check("COST-004", "COST_MANAGEMENT", "Budget status endpoint exists",
           "API endpoint reports current budget usage and limits.",
           "AUTOMATED", "MEDIUM", True, False,
           "cost_routes.py has budget status endpoint.",
           "Implement budget status API endpoint.", "Platform Team"),
    _check("COST-005", "COST_MANAGEMENT", "Cost anomaly detector exists",
           "System detects unusual cost spikes and alerts.",
           "AUTOMATED", "MEDIUM", True, False,
           "alerting module or cost service has anomaly detection.",
           "Implement cost anomaly detection.", "Platform Team"),
    _check("COST-006", "COST_MANAGEMENT", "Cost alert placeholder exists",
           "Alert configuration for budget exceeded or cost anomaly exists.",
           "AUTOMATED", "MEDIUM", True, False,
           "monitoring/alerts/ contains cost alert definition.",
           "Create cost alert definitions in monitoring/alerts/.", "Platform Team"),

    # -------------------------------------------------------------------------
    # P. DEVOPS AND RELEASE MANAGEMENT
    # -------------------------------------------------------------------------
    _check("DEVOPS-001", "DEVOPS_AND_RELEASE_MANAGEMENT", "Azure DevOps pipeline exists",
           "Azure DevOps pipeline YAML exists for CI/CD.",
           "AUTOMATED", "HIGH", True, False,
           "pipelines/ folder contains .yml pipeline file.",
           "Create Azure DevOps pipeline YAML.", "DevOps Team"),
    _check("DEVOPS-002", "DEVOPS_AND_RELEASE_MANAGEMENT", "Infra validation stage exists",
           "Pipeline includes a Bicep what-if validation stage.",
           "AUTOMATED", "HIGH", True, False,
           "Pipeline YAML contains infra validation step.",
           "Add Bicep what-if validation stage to pipeline.", "DevOps Team"),
    _check("DEVOPS-003", "DEVOPS_AND_RELEASE_MANAGEMENT", "Security scan stage exists",
           "Pipeline includes a secrets/security scan stage.",
           "AUTOMATED", "HIGH", True, False,
           "Pipeline YAML contains security scan step.",
           "Add secrets scan stage to pipeline.", "DevOps Team"),
    _check("DEVOPS-004", "DEVOPS_AND_RELEASE_MANAGEMENT", "Bicep what-if script exists",
           "A script exists to run Bicep what-if before deployment.",
           "AUTOMATED", "MEDIUM", True, False,
           "scripts/ folder contains bicep-what-if script.",
           "Create Bicep what-if script in scripts/.", "DevOps Team"),
    _check("DEVOPS-005", "DEVOPS_AND_RELEASE_MANAGEMENT", "Environment parameter files exist",
           "Bicep parameter files exist for dev and prod environments.",
           "AUTOMATED", "HIGH", True, False,
           "infra/bicep/parameters/dev.parameters.json exists.",
           "Create environment-specific parameter files.", "DevOps Team"),
    _check("DEVOPS-006", "DEVOPS_AND_RELEASE_MANAGEMENT", "Rollback guide exists",
           "A rollback guide documents how to revert a failed deployment.",
           "AUTOMATED", "HIGH", True, False,
           "docs/runbooks/ contains rollback-guide.md.",
           "Create rollback guide runbook.", "DevOps Team"),
    _check("DEVOPS-007", "DEVOPS_AND_RELEASE_MANAGEMENT", "No secrets in pipeline YAML",
           "Pipeline YAML contains no hardcoded secrets or API keys.",
           "AUTOMATED", "BLOCKER", True, False,
           "Secret scan of pipelines/ finds no pattern matches.",
           "Remove all secrets from pipeline YAML; use pipeline variables.", "DevOps Team"),

    # -------------------------------------------------------------------------
    # Q. TESTING AND QUALITY
    # -------------------------------------------------------------------------
    _check("TEST-001", "TESTING_AND_QUALITY", "Backend tests exist",
           "Backend unit and integration tests exist and cover key functionality.",
           "AUTOMATED", "HIGH", True, False,
           "backend/tests/ folder with test files exists.",
           "Create backend test suite.", "Development Team"),
    _check("TEST-002", "TESTING_AND_QUALITY", "Agent tests exist",
           "Agent layer has unit tests.",
           "AUTOMATED", "HIGH", True, False,
           "backend/tests/ contains agent test files.",
           "Create agent unit tests.", "Development Team"),
    _check("TEST-003", "TESTING_AND_QUALITY", "RAG tests exist",
           "RAG retrieval has unit tests.",
           "AUTOMATED", "HIGH", True, False,
           "backend/tests/ contains RAG test files.",
           "Create RAG unit tests.", "Development Team"),
    _check("TEST-004", "TESTING_AND_QUALITY", "Frontend TypeScript build passes",
           "Next.js frontend builds without TypeScript errors.",
           "AUTOMATED", "HIGH", True, False,
           "npm run build completes without errors.",
           "Fix all TypeScript errors in frontend build.", "Development Team"),
    _check("TEST-005", "TESTING_AND_QUALITY", "Security tests exist",
           "Security-specific tests exist for auth, permissions, and guardrails.",
           "AUTOMATED", "HIGH", True, False,
           "backend/tests/ contains security or auth test files.",
           "Create security test suite.", "Development Team"),
    _check("TEST-006", "TESTING_AND_QUALITY", "AI evaluation tests exist",
           "Tests exist for AI output quality and guardrail behavior.",
           "AUTOMATED", "MEDIUM", True, False,
           "tests/ or backend/tests/ contains AI eval test files.",
           "Create AI evaluation tests.", "Development Team"),
    _check("TEST-007", "TESTING_AND_QUALITY", "Human review workflow tests exist",
           "Tests cover the human review submission and audit trail.",
           "AUTOMATED", "HIGH", True, False,
           "backend/tests/ contains review workflow test files.",
           "Create human review workflow tests.", "Development Team"),
    _check("TEST-008", "TESTING_AND_QUALITY", "Audit route tests exist",
           "Tests cover audit event creation and retrieval APIs.",
           "AUTOMATED", "HIGH", True, False,
           "backend/tests/ contains audit route test files.",
           "Create audit API tests.", "Development Team"),

    # -------------------------------------------------------------------------
    # R. OPERATIONS AND SUPPORT
    # -------------------------------------------------------------------------
    _check("OPS-001", "OPERATIONS_AND_SUPPORT", "Operations runbook exists",
           "An operations runbook documents day-to-day operational procedures.",
           "AUTOMATED", "HIGH", True, False,
           "docs/runbooks/ contains operations runbook.",
           "Create operations runbook in docs/runbooks/.", "Platform Team"),
    _check("OPS-002", "OPERATIONS_AND_SUPPORT", "Incident response documentation exists",
           "Incident response procedures are documented.",
           "AUTOMATED", "HIGH", True, False,
           "docs/runbooks/ or docs/alerting-and-incident-response.md exists.",
           "Create incident response documentation.", "Platform Team"),
    _check("OPS-003", "OPERATIONS_AND_SUPPORT", "Monitoring guide exists",
           "A monitoring guide describes how to use observability tools.",
           "AUTOMATED", "MEDIUM", True, False,
           "docs/production-observability-monitoring.md exists.",
           "Create monitoring guide.", "Platform Team"),
    _check("OPS-004", "OPERATIONS_AND_SUPPORT", "Rollback guide exists",
           "Rollback procedures for failed deployments are documented.",
           "AUTOMATED", "HIGH", True, False,
           "docs/runbooks/ contains rollback guide.",
           "Create rollback guide in docs/runbooks/.", "Platform Team"),
    _check("OPS-005", "OPERATIONS_AND_SUPPORT", "Admin configuration panel exists",
           "Admin panel exists for runtime configuration changes.",
           "AUTOMATED", "HIGH", True, False,
           "frontend/src/app/admin/ and backend/app/admin/ exist.",
           "Implement admin configuration panel.", "Platform Team"),
    _check("OPS-006", "OPERATIONS_AND_SUPPORT", "Notification system exists",
           "In-app or Teams notification system is implemented.",
           "AUTOMATED", "MEDIUM", True, False,
           "backend/app/notifications/ module exists.",
           "Implement notification system.", "Platform Team"),
    _check("OPS-007", "OPERATIONS_AND_SUPPORT", "Case assignment queue exists",
           "Case assignment and investigator queue management is implemented.",
           "AUTOMATED", "HIGH", True, False,
           "backend/app/assignment/ and frontend/src/app/queues/ exist.",
           "Implement case assignment queue.", "Platform Team"),

    # -------------------------------------------------------------------------
    # S. DOCUMENTATION
    # -------------------------------------------------------------------------
    _check("DOC-001", "DOCUMENTATION", "README exists",
           "A comprehensive README exists at the project root.",
           "AUTOMATED", "HIGH", True, False,
           "README.md exists with project overview.",
           "Create or update README.md.", "Development Team"),
    _check("DOC-002", "DOCUMENTATION", "Architecture docs exist",
           "Architecture documentation exists in docs/ folder.",
           "AUTOMATED", "HIGH", True, False,
           "docs/ folder contains architecture documentation.",
           "Create architecture documentation.", "Solution Architect"),
    _check("DOC-003", "DOCUMENTATION", "Security docs exist",
           "Security documentation exists describing auth and secrets management.",
           "AUTOMATED", "HIGH", True, False,
           "docs/ contains security or deployment hardening docs.",
           "Create security documentation.", "Security Team"),
    _check("DOC-004", "DOCUMENTATION", "RAG docs exist",
           "RAG architecture and usage is documented.",
           "AUTOMATED", "MEDIUM", True, False,
           "docs/azure-ai-search-production-rag.md exists.",
           "Create RAG documentation.", "Platform Team"),
    _check("DOC-005", "DOCUMENTATION", "Deployment hardening docs exist",
           "Deployment hardening guide exists for production deployment.",
           "AUTOMATED", "HIGH", True, False,
           "docs/deployment-hardening-key-vault-private-endpoints-managed-identity.md exists.",
           "Create deployment hardening documentation.", "Platform Team"),
    _check("DOC-006", "DOCUMENTATION", "Data retention docs exist",
           "Data retention policy is documented.",
           "AUTOMATED", "HIGH", True, False,
           "docs/data-retention-compliance-policy.md exists.",
           "Create data retention documentation.", "Compliance Team"),
    _check("DOC-007", "DOCUMENTATION", "Production readiness checklist docs exist",
           "The production readiness checklist framework is documented.",
           "AUTOMATED", "HIGH", True, False,
           "docs/end-to-end-production-readiness-checklist.md exists.",
           "Create production readiness checklist documentation.", "Solution Architect"),

    # -------------------------------------------------------------------------
    # T. BUSINESS READINESS
    # -------------------------------------------------------------------------
    _check("BUS-001", "BUSINESS_READINESS", "Fraud investigator workflow documented",
           "The end-to-end fraud investigator workflow is documented.",
           "MANUAL", "HIGH", False, True,
           "Workflow diagram or process document.",
           "Document fraud investigator workflow for training.", "Fraud Operations Team"),
    _check("BUS-002", "BUSINESS_READINESS", "Human review policy documented",
           "Human review decision policy and authority matrix are documented.",
           "MANUAL", "HIGH", False, True,
           "Human review policy document signed by Fraud Ops.",
           "Create and sign human review policy document.", "Fraud Operations Team"),
    _check("BUS-003", "BUSINESS_READINESS", "AI limitation statement documented",
           "Documented statement of AI system limitations for business stakeholders.",
           "MANUAL", "HIGH", False, True,
           "AI limitation statement reviewed by AI Governance Team.",
           "Create AI limitation statement document.", "AI Governance Team"),
    _check("BUS-004", "BUSINESS_READINESS", "Business KPIs dashboard exists",
           "Frontend dashboard showing business KPIs (override rate, SLA, etc.) exists.",
           "AUTOMATED", "MEDIUM", True, False,
           "frontend/src/app/metrics/ or dashboard with KPI metrics exists.",
           "Implement business KPIs dashboard.", "Fraud Operations Team"),
    _check("BUS-005", "BUSINESS_READINESS", "Training/demo guide exists",
           "A guide for training fraud investigators on the system exists.",
           "MANUAL", "MEDIUM", False, True,
           "Training guide or demo script document.",
           "Create training and demo guide for fraud investigators.", "Fraud Operations Team"),
    _check("BUS-006", "BUSINESS_READINESS", "Go-live risk register exists",
           "A risk register for the go-live decision is maintained.",
           "AUTOMATED", "HIGH", True, False,
           "data/synthetic/readiness_risk_register.json exists.",
           "Create and maintain the go-live risk register.", "Solution Architect"),
]


def get_all_checks() -> list[dict]:
    """Return all check definitions."""
    return READINESS_CHECKS


def get_checks_by_category(category: str) -> list[dict]:
    """Return checks for a specific category."""
    return [c for c in READINESS_CHECKS if c["category"] == category]


def get_check_by_id(check_id: str) -> dict | None:
    """Return a single check definition by ID."""
    for c in READINESS_CHECKS:
        if c["check_id"] == check_id:
            return c
    return None


def get_all_categories() -> list[str]:
    """Return all unique categories in the registry."""
    seen = []
    for c in READINESS_CHECKS:
        if c["category"] not in seen:
            seen.append(c["category"])
    return seen
