from enum import StrEnum


class CaseStatus(StrEnum):
    NEW = "NEW"
    AI_INVESTIGATION_IN_PROGRESS = "AI_INVESTIGATION_IN_PROGRESS"
    AI_INVESTIGATION_COMPLETED = "AI_INVESTIGATION_COMPLETED"
    PENDING_HUMAN_REVIEW = "PENDING_HUMAN_REVIEW"
    APPROVED = "APPROVED"
    HELD = "HELD"
    ESCALATED = "ESCALATED"
    REJECTED = "REJECTED"
    CLOSED = "CLOSED"


class ReviewDecision(StrEnum):
    APPROVE = "APPROVE"
    HOLD = "HOLD"
    ESCALATE = "ESCALATE"
    REJECT = "REJECT"


class ReviewerRole(StrEnum):
    FRAUD_ANALYST = "FRAUD_ANALYST"
    FRAUD_MANAGER = "FRAUD_MANAGER"
    COMPLIANCE_OFFICER = "COMPLIANCE_OFFICER"
    AUDITOR = "AUDITOR"
    SYSTEM = "SYSTEM"
    UNKNOWN = "UNKNOWN"


class ReasonCode(StrEnum):
    CUSTOMER_CONFIRMED = "CUSTOMER_CONFIRMED"
    SUSPICIOUS_DEVICE = "SUSPICIOUS_DEVICE"
    NEW_BENEFICIARY_RISK = "NEW_BENEFICIARY_RISK"
    HIGH_VALUE_TRANSFER = "HIGH_VALUE_TRANSFER"
    POLICY_THRESHOLD_BREACH = "POLICY_THRESHOLD_BREACH"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    FALSE_POSITIVE = "FALSE_POSITIVE"
    ESCALATE_TO_AML = "ESCALATE_TO_AML"


class AuditEventType(StrEnum):
    CASE_CREATED = "CASE_CREATED"
    CASE_VIEWED = "CASE_VIEWED"
    CASE_STATUS_CHANGED = "CASE_STATUS_CHANGED"
    AI_INVESTIGATION_STARTED = "AI_INVESTIGATION_STARTED"
    AI_INVESTIGATION_COMPLETED = "AI_INVESTIGATION_COMPLETED"
    AI_INVESTIGATION_FAILED = "AI_INVESTIGATION_FAILED"
    AGENT_EXECUTION_STARTED = "AGENT_EXECUTION_STARTED"
    AGENT_EXECUTION_COMPLETED = "AGENT_EXECUTION_COMPLETED"
    AGENT_EXECUTION_FAILED = "AGENT_EXECUTION_FAILED"
    RAG_RETRIEVAL_STARTED = "RAG_RETRIEVAL_STARTED"
    RAG_RETRIEVAL_COMPLETED = "RAG_RETRIEVAL_COMPLETED"
    RAG_RETRIEVAL_FAILED = "RAG_RETRIEVAL_FAILED"
    PENDING_HUMAN_REVIEW_SET = "PENDING_HUMAN_REVIEW_SET"
    HUMAN_DECISION_SUBMITTED = "HUMAN_DECISION_SUBMITTED"
    HUMAN_OVERRIDE_DETECTED = "HUMAN_OVERRIDE_DETECTED"
    CASE_CLOSED = "CASE_CLOSED"
    API_ERROR = "API_ERROR"
    SECURITY_EVENT = "SECURITY_EVENT"


AUDIT_EVENT_CATEGORY_BY_TYPE: dict[AuditEventType, str] = {
    AuditEventType.CASE_CREATED: "CASE",
    AuditEventType.CASE_VIEWED: "CASE",
    AuditEventType.CASE_STATUS_CHANGED: "CASE",
    AuditEventType.PENDING_HUMAN_REVIEW_SET: "CASE",
    AuditEventType.CASE_CLOSED: "CASE",
    AuditEventType.AI_INVESTIGATION_STARTED: "AI",
    AuditEventType.AI_INVESTIGATION_COMPLETED: "AI",
    AuditEventType.AI_INVESTIGATION_FAILED: "AI",
    AuditEventType.AGENT_EXECUTION_STARTED: "AGENT",
    AuditEventType.AGENT_EXECUTION_COMPLETED: "AGENT",
    AuditEventType.AGENT_EXECUTION_FAILED: "AGENT",
    AuditEventType.RAG_RETRIEVAL_STARTED: "RAG",
    AuditEventType.RAG_RETRIEVAL_COMPLETED: "RAG",
    AuditEventType.RAG_RETRIEVAL_FAILED: "RAG",
    AuditEventType.HUMAN_DECISION_SUBMITTED: "HUMAN_REVIEW",
    AuditEventType.HUMAN_OVERRIDE_DETECTED: "HUMAN_REVIEW",
    AuditEventType.API_ERROR: "ERROR",
    AuditEventType.SECURITY_EVENT: "SECURITY",
}


ALLOWED_STATUS_TRANSITIONS: dict[CaseStatus, set[CaseStatus]] = {
    CaseStatus.NEW: {CaseStatus.AI_INVESTIGATION_IN_PROGRESS},
    CaseStatus.AI_INVESTIGATION_IN_PROGRESS: {CaseStatus.AI_INVESTIGATION_COMPLETED},
    CaseStatus.AI_INVESTIGATION_COMPLETED: {CaseStatus.PENDING_HUMAN_REVIEW},
    CaseStatus.PENDING_HUMAN_REVIEW: {
        CaseStatus.APPROVED,
        CaseStatus.HELD,
        CaseStatus.ESCALATED,
        CaseStatus.REJECTED,
    },
    CaseStatus.APPROVED: {CaseStatus.CLOSED},
    CaseStatus.HELD: {CaseStatus.CLOSED},
    CaseStatus.ESCALATED: {CaseStatus.CLOSED},
    CaseStatus.REJECTED: {CaseStatus.CLOSED},
    CaseStatus.CLOSED: set(),
}


DECISION_TO_STATUS: dict[ReviewDecision, CaseStatus] = {
    ReviewDecision.APPROVE: CaseStatus.APPROVED,
    ReviewDecision.HOLD: CaseStatus.HELD,
    ReviewDecision.ESCALATE: CaseStatus.ESCALATED,
    ReviewDecision.REJECT: CaseStatus.REJECTED,
}
