from enum import StrEnum


class CaseStatus(StrEnum):
    NEW = "NEW"
    AI_INVESTIGATION_IN_PROGRESS = "AI_INVESTIGATION_IN_PROGRESS"
    AI_INVESTIGATION_COMPLETED = "AI_INVESTIGATION_COMPLETED"
    PENDING_HUMAN_REVIEW = "PENDING_HUMAN_REVIEW"
    APPROVED = "APPROVED"
    HELD = "HELD"
    ESCALATED = "ESCALATED"
    REJECTED = "REJECTED"
    CLOSED = "CLOSED"


class ReviewDecision(StrEnum):
    APPROVE = "APPROVE"
    HOLD = "HOLD"
    ESCALATE = "ESCALATE"
    REJECT = "REJECT"


Decision = ReviewDecision


class OverrideComparisonStatus(StrEnum):
    MATCHED = "MATCHED"
    OVERRIDDEN = "OVERRIDDEN"
    AI_RECOMMENDATION_MISSING = "AI_RECOMMENDATION_MISSING"
    NOT_APPLICABLE = "NOT_APPLICABLE"


def normalize_decision(value: str | None) -> str | None:
    if value is None:
        return None

    normalized = value.strip().upper()
    if not normalized:
        return None

    legacy_map = {
        "APPROVED": ReviewDecision.APPROVE.value,
        "HELD": ReviewDecision.HOLD.value,
        "ESCALATED": ReviewDecision.ESCALATE.value,
        "REJECTED": ReviewDecision.REJECT.value,
    }
    normalized = legacy_map.get(normalized, normalized)
    return ReviewDecision(normalized).value


class ReviewerRole(StrEnum):
    FRAUD_ANALYST = "FRAUD_ANALYST"
    FRAUD_MANAGER = "FRAUD_MANAGER"
    COMPLIANCE_OFFICER = "COMPLIANCE_OFFICER"
    AUDITOR = "AUDITOR"
    ADMIN = "ADMIN"
    SYSTEM = "SYSTEM"
    UNKNOWN = "UNKNOWN"


class ReasonCode(StrEnum):
    CUSTOMER_CONFIRMED = "CUSTOMER_CONFIRMED"
    SUSPICIOUS_DEVICE = "SUSPICIOUS_DEVICE"
    NEW_BENEFICIARY_RISK = "NEW_BENEFICIARY_RISK"
    HIGH_VALUE_TRANSFER = "HIGH_VALUE_TRANSFER"
    POLICY_THRESHOLD_BREACH = "POLICY_THRESHOLD_BREACH"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    FALSE_POSITIVE = "FALSE_POSITIVE"
    ESCALATE_TO_AML = "ESCALATE_TO_AML"


class AlertSeverity(StrEnum):
    SEV0_CRITICAL = "SEV0_CRITICAL"
    SEV1_HIGH = "SEV1_HIGH"
    SEV2_MEDIUM = "SEV2_MEDIUM"
    SEV3_LOW = "SEV3_LOW"


class AssignmentStatus(StrEnum):
    UNASSIGNED = "UNASSIGNED"
    ASSIGNED = "ASSIGNED"
    ACCEPTED = "ACCEPTED"
    RELEASED = "RELEASED"
    TRANSFERRED = "TRANSFERRED"


class AssignmentPriority(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class SlaStatus(StrEnum):
    ON_TRACK = "ON_TRACK"
    AT_RISK = "AT_RISK"
    BREACHED = "BREACHED"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class NotificationEventType(StrEnum):
    CASE_ASSIGNED = "CASE_ASSIGNED"
    CASE_REASSIGNED = "CASE_REASSIGNED"
    CASE_ACCEPTED = "CASE_ACCEPTED"
    CASE_RELEASED = "CASE_RELEASED"
    CASE_TRANSFERRED = "CASE_TRANSFERRED"
    CASE_STATUS_CHANGED = "CASE_STATUS_CHANGED"
    AI_INVESTIGATION_COMPLETED = "AI_INVESTIGATION_COMPLETED"
    HUMAN_REVIEW_REQUIRED = "HUMAN_REVIEW_REQUIRED"
    HUMAN_DECISION_SUBMITTED = "HUMAN_DECISION_SUBMITTED"
    HUMAN_OVERRIDE_DETECTED = "HUMAN_OVERRIDE_DETECTED"
    CASE_CLOSED = "CASE_CLOSED"
    SLA_AT_RISK = "SLA_AT_RISK"
    SLA_BREACHED = "SLA_BREACHED"
    ALERT_CREATED = "ALERT_CREATED"
    INCIDENT_CREATED = "INCIDENT_CREATED"
    INCIDENT_ASSIGNED = "INCIDENT_ASSIGNED"
    INCIDENT_STATUS_CHANGED = "INCIDENT_STATUS_CHANGED"
    INCIDENT_CLOSED = "INCIDENT_CLOSED"
    HIGH_HUMAN_OVERRIDE_RATE = "HIGH_HUMAN_OVERRIDE_RATE"
    LOW_POLICY_CITATION_ACCURACY = "LOW_POLICY_CITATION_ACCURACY"
    HIGH_LLM_FAILURE_RATE = "HIGH_LLM_FAILURE_RATE"
    PROMPT_INJECTION_DETECTED = "PROMPT_INJECTION_DETECTED"
    GUARDRAIL_VIOLATION_DETECTED = "GUARDRAIL_VIOLATION_DETECTED"
    HIGH_TOKEN_USAGE = "HIGH_TOKEN_USAGE"
    BUDGET_WARNING = "BUDGET_WARNING"
    BUDGET_EXCEEDED = "BUDGET_EXCEEDED"
    SYSTEM_HEALTH_DEGRADED = "SYSTEM_HEALTH_DEGRADED"
    ADMIN_CONFIG_UPDATED = "ADMIN_CONFIG_UPDATED"
    FEATURE_FLAG_UPDATED = "FEATURE_FLAG_UPDATED"
    AI_FEEDBACK_CRITICAL_SUBMITTED = "AI_FEEDBACK_CRITICAL_SUBMITTED"
    AI_FEEDBACK_BACKLOG_CREATED = "AI_FEEDBACK_BACKLOG_CREATED"
    RETENTION_REVIEW_REQUIRED = "RETENTION_REVIEW_REQUIRED"
    LEGAL_HOLD_CREATED = "LEGAL_HOLD_CREATED"
    LEGAL_HOLD_RELEASED = "LEGAL_HOLD_RELEASED"
    COMPLIANCE_EXPORT_COMPLETED = "COMPLIANCE_EXPORT_COMPLETED"
    PURGE_EXECUTED = "PURGE_EXECUTED"
    PRODUCTION_READINESS_NOT_READY = "PRODUCTION_READINESS_NOT_READY"
    PRODUCTION_READINESS_BLOCKER_FOUND = "PRODUCTION_READINESS_BLOCKER_FOUND"
    PRODUCTION_READINESS_REPORT_EXPORTED = "PRODUCTION_READINESS_REPORT_EXPORTED"


class NotificationPriority(StrEnum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INFO = "INFO"


class NotificationChannel(StrEnum):
    IN_APP = "IN_APP"
    LOCAL = "LOCAL"
    EMAIL = "EMAIL"
    TEAMS = "TEAMS"
    WEBHOOK = "WEBHOOK"


class NotificationStatus(StrEnum):
    PENDING = "PENDING"
    SENT = "SENT"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"
    READ = "READ"
    ARCHIVED = "ARCHIVED"


class NotificationRecipientType(StrEnum):
    USER = "USER"
    ROLE = "ROLE"
    TEAM = "TEAM"
    SYSTEM = "SYSTEM"


class FeedbackTargetType(StrEnum):
    INVESTIGATION_SUMMARY = "INVESTIGATION_SUMMARY"
    AI_RECOMMENDATION = "AI_RECOMMENDATION"
    POLICY_CITATION = "POLICY_CITATION"
    SIMILAR_CASE_RETRIEVAL = "SIMILAR_CASE_RETRIEVAL"
    RISK_INDICATOR = "RISK_INDICATOR"
    REVIEWER_VALIDATION = "REVIEWER_VALIDATION"
    AGENT_TRACE = "AGENT_TRACE"
    OVERALL_AI_OUTPUT = "OVERALL_AI_OUTPUT"


class FeedbackRating(StrEnum):
    VERY_POOR = "VERY_POOR"
    POOR = "POOR"
    ACCEPTABLE = "ACCEPTABLE"
    GOOD = "GOOD"
    EXCELLENT = "EXCELLENT"


class FeedbackIssueType(StrEnum):
    INCORRECT_RECOMMENDATION = "INCORRECT_RECOMMENDATION"
    MISSING_EVIDENCE = "MISSING_EVIDENCE"
    UNSUPPORTED_CLAIM = "UNSUPPORTED_CLAIM"
    WRONG_POLICY_CITATION = "WRONG_POLICY_CITATION"
    MISSING_POLICY_CITATION = "MISSING_POLICY_CITATION"
    IRRELEVANT_SIMILAR_CASE = "IRRELEVANT_SIMILAR_CASE"
    MISSING_SIMILAR_CASE = "MISSING_SIMILAR_CASE"
    POOR_EXPLANATION = "POOR_EXPLANATION"
    TOO_VERBOSE = "TOO_VERBOSE"
    TOO_SHORT = "TOO_SHORT"
    HALLUCINATION_SUSPECTED = "HALLUCINATION_SUSPECTED"
    SAFETY_CONCERN = "SAFETY_CONCERN"
    PII_CONCERN = "PII_CONCERN"
    PROMPT_INJECTION_CONCERN = "PROMPT_INJECTION_CONCERN"
    OTHER = "OTHER"


class FeedbackDisposition(StrEnum):
    NEW = "NEW"
    TRIAGED = "TRIAGED"
    ACCEPTED_FOR_IMPROVEMENT = "ACCEPTED_FOR_IMPROVEMENT"
    REJECTED_NO_ACTION = "REJECTED_NO_ACTION"
    CONVERTED_TO_EVAL_CASE = "CONVERTED_TO_EVAL_CASE"
    PROMPT_BACKLOG_CREATED = "PROMPT_BACKLOG_CREATED"
    RAG_BACKLOG_CREATED = "RAG_BACKLOG_CREATED"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"


class FeedbackSeverity(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class DataCategory(StrEnum):
    FRAUD_CASE = "FRAUD_CASE"
    AUDIT_EVENT = "AUDIT_EVENT"
    HUMAN_REVIEW = "HUMAN_REVIEW"
    AI_INVESTIGATION_OUTPUT = "AI_INVESTIGATION_OUTPUT"
    AGENT_TRACE = "AGENT_TRACE"
    RAG_RETRIEVAL_RECORD = "RAG_RETRIEVAL_RECORD"
    POLICY_DOCUMENT = "POLICY_DOCUMENT"
    HISTORICAL_CASE_DOCUMENT = "HISTORICAL_CASE_DOCUMENT"
    FEEDBACK_RECORD = "FEEDBACK_RECORD"
    NOTIFICATION_RECORD = "NOTIFICATION_RECORD"
    INCIDENT_RECORD = "INCIDENT_RECORD"
    ALERT_RECORD = "ALERT_RECORD"
    COST_RECORD = "COST_RECORD"
    TELEMETRY_RECORD = "TELEMETRY_RECORD"
    CONFIG_HISTORY = "CONFIG_HISTORY"
    ASSIGNMENT_HISTORY = "ASSIGNMENT_HISTORY"
    EXPORT_FILE = "EXPORT_FILE"


class DataClassification(StrEnum):
    PUBLIC = "PUBLIC"
    INTERNAL = "INTERNAL"
    CONFIDENTIAL = "CONFIDENTIAL"
    RESTRICTED = "RESTRICTED"


class RetentionAction(StrEnum):
    KEEP = "KEEP"
    ARCHIVE = "ARCHIVE"
    PURGE = "PURGE"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    LEGAL_HOLD = "LEGAL_HOLD"
    EXEMPT = "EXEMPT"


class RetentionStatus(StrEnum):
    ACTIVE = "ACTIVE"
    ARCHIVE_ELIGIBLE = "ARCHIVE_ELIGIBLE"
    ARCHIVED = "ARCHIVED"
    PURGE_ELIGIBLE = "PURGE_ELIGIBLE"
    PURGED = "PURGED"
    LEGAL_HOLD = "LEGAL_HOLD"
    EXEMPT = "EXEMPT"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


class LegalHoldStatus(StrEnum):
    NONE = "NONE"
    ACTIVE = "ACTIVE"
    RELEASED = "RELEASED"


class ComplianceExportStatus(StrEnum):
    REQUESTED = "REQUESTED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class ReadinessCategory(str):
    ARCHITECTURE = "ARCHITECTURE"
    SECURITY = "SECURITY"
    IDENTITY_AND_ACCESS = "IDENTITY_AND_ACCESS"
    SECRETS_AND_KEY_MANAGEMENT = "SECRETS_AND_KEY_MANAGEMENT"
    NETWORKING = "NETWORKING"
    AI_SAFETY_AND_GUARDRAILS = "AI_SAFETY_AND_GUARDRAILS"
    RAG_AND_KNOWLEDGE_GROUNDING = "RAG_AND_KNOWLEDGE_GROUNDING"
    HUMAN_IN_THE_LOOP = "HUMAN_IN_THE_LOOP"
    AUDIT_AND_COMPLIANCE = "AUDIT_AND_COMPLIANCE"
    DATA_RETENTION = "DATA_RETENTION"
    OBSERVABILITY = "OBSERVABILITY"
    ALERTING_AND_INCIDENT_RESPONSE = "ALERTING_AND_INCIDENT_RESPONSE"
    RELIABILITY_AND_RESILIENCE = "RELIABILITY_AND_RESILIENCE"
    PERFORMANCE_AND_SCALABILITY = "PERFORMANCE_AND_SCALABILITY"
    COST_MANAGEMENT = "COST_MANAGEMENT"
    DEVOPS_AND_RELEASE_MANAGEMENT = "DEVOPS_AND_RELEASE_MANAGEMENT"
    TESTING_AND_QUALITY = "TESTING_AND_QUALITY"
    OPERATIONS_AND_SUPPORT = "OPERATIONS_AND_SUPPORT"
    DOCUMENTATION = "DOCUMENTATION"
    BUSINESS_READINESS = "BUSINESS_READINESS"


READINESS_CATEGORIES: list[str] = [
    "ARCHITECTURE",
    "SECURITY",
    "IDENTITY_AND_ACCESS",
    "SECRETS_AND_KEY_MANAGEMENT",
    "NETWORKING",
    "AI_SAFETY_AND_GUARDRAILS",
    "RAG_AND_KNOWLEDGE_GROUNDING",
    "HUMAN_IN_THE_LOOP",
    "AUDIT_AND_COMPLIANCE",
    "DATA_RETENTION",
    "OBSERVABILITY",
    "ALERTING_AND_INCIDENT_RESPONSE",
    "RELIABILITY_AND_RESILIENCE",
    "PERFORMANCE_AND_SCALABILITY",
    "COST_MANAGEMENT",
    "DEVOPS_AND_RELEASE_MANAGEMENT",
    "TESTING_AND_QUALITY",
    "OPERATIONS_AND_SUPPORT",
    "DOCUMENTATION",
    "BUSINESS_READINESS",
]


class ReadinessStatus(StrEnum):
    PASS = "PASS"
    FAIL = "FAIL"
    WARNING = "WARNING"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"
    NOT_CHECKED = "NOT_CHECKED"


class ReadinessSeverity(StrEnum):
    BLOCKER = "BLOCKER"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INFO = "INFO"


class GoLiveDecision(StrEnum):
    READY = "READY"
    READY_WITH_RISKS = "READY_WITH_RISKS"
    NOT_READY = "NOT_READY"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"


class ReadinessCheckType(StrEnum):
    AUTOMATED = "AUTOMATED"
    MANUAL = "MANUAL"
    HYBRID = "HYBRID"


class ReadinessRiskStatus(StrEnum):
    OPEN = "OPEN"
    MITIGATED = "MITIGATED"
    ACCEPTED = "ACCEPTED"
    CLOSED = "CLOSED"


class AlertType(StrEnum):
    HIGH_API_ERROR_RATE = "HIGH_API_ERROR_RATE"
    HIGH_API_LATENCY = "HIGH_API_LATENCY"
    AUTH_FAILURE_SPIKE = "AUTH_FAILURE_SPIKE"
    AUTHORIZATION_FAILURE_SPIKE = "AUTHORIZATION_FAILURE_SPIKE"
    HIGH_AGENT_FAILURE_RATE = "HIGH_AGENT_FAILURE_RATE"
    AGENT_EXECUTION_TIMEOUT = "AGENT_EXECUTION_TIMEOUT"
    AGENT_FALLBACK_SPIKE = "AGENT_FALLBACK_SPIKE"
    HIGH_RAG_FAILURE_RATE = "HIGH_RAG_FAILURE_RATE"
    HIGH_RAG_EMPTY_RESULT_RATE = "HIGH_RAG_EMPTY_RESULT_RATE"
    CITATION_VALIDATION_FAILURE = "CITATION_VALIDATION_FAILURE"
    POLICY_CITATION_ACCURACY_LOW = "POLICY_CITATION_ACCURACY_LOW"
    HIGH_LLM_FAILURE_RATE = "HIGH_LLM_FAILURE_RATE"
    HIGH_LLM_LATENCY = "HIGH_LLM_LATENCY"
    HIGH_TOKEN_USAGE = "HIGH_TOKEN_USAGE"
    HIGH_COST_ESTIMATE = "HIGH_COST_ESTIMATE"
    BUDGET_WARNING = "BUDGET_WARNING"
    BUDGET_EXCEEDED = "BUDGET_EXCEEDED"
    COST_ANOMALY_DETECTED = "COST_ANOMALY_DETECTED"
    HIGH_CASE_COST_DETECTED = "HIGH_CASE_COST_DETECTED"
    HIGH_AGENT_COST_DETECTED = "HIGH_AGENT_COST_DETECTED"
    LLM_JSON_PARSE_FAILURE_SPIKE = "LLM_JSON_PARSE_FAILURE_SPIKE"
    LLM_OUTPUT_VALIDATION_FAILURE_SPIKE = "LLM_OUTPUT_VALIDATION_FAILURE_SPIKE"
    PROMPT_INJECTION_DETECTED = "PROMPT_INJECTION_DETECTED"
    GUARDRAIL_VIOLATION_DETECTED = "GUARDRAIL_VIOLATION_DETECTED"
    PII_REDACTION_FAILURE = "PII_REDACTION_FAILURE"
    HIGH_HUMAN_OVERRIDE_RATE = "HIGH_HUMAN_OVERRIDE_RATE"
    CASES_STUCK_PENDING_REVIEW = "CASES_STUCK_PENDING_REVIEW"
    HIGH_ESCALATION_RATE = "HIGH_ESCALATION_RATE"
    AUDIT_LOG_WRITE_FAILURE = "AUDIT_LOG_WRITE_FAILURE"
    TELEMETRY_EMISSION_FAILURE = "TELEMETRY_EMISSION_FAILURE"
    DATA_FILE_ACCESS_FAILURE = "DATA_FILE_ACCESS_FAILURE"
    HIGH_NEGATIVE_AI_FEEDBACK_RATE = "HIGH_NEGATIVE_AI_FEEDBACK_RATE"
    CRITICAL_AI_FEEDBACK_SUBMITTED = "CRITICAL_AI_FEEDBACK_SUBMITTED"
    HIGH_WRONG_CITATION_FEEDBACK_RATE = "HIGH_WRONG_CITATION_FEEDBACK_RATE"
    HIGH_INCORRECT_RECOMMENDATION_FEEDBACK_RATE = "HIGH_INCORRECT_RECOMMENDATION_FEEDBACK_RATE"
    RETENTION_PURGE_FAILED = "RETENTION_PURGE_FAILED"
    RETENTION_PURGE_BLOCKED_LEGAL_HOLD = "RETENTION_PURGE_BLOCKED_LEGAL_HOLD"
    HIGH_PURGE_CANDIDATE_COUNT = "HIGH_PURGE_CANDIDATE_COUNT"
    COMPLIANCE_EXPORT_FAILED = "COMPLIANCE_EXPORT_FAILED"
    LEGAL_HOLD_RELEASED = "LEGAL_HOLD_RELEASED"


class IncidentStatus(StrEnum):
    OPEN = "OPEN"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    INVESTIGATING = "INVESTIGATING"
    MITIGATED = "MITIGATED"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"


class AuditEventType(StrEnum):
    CASE_CREATED = "CASE_CREATED"
    CASE_VIEWED = "CASE_VIEWED"
    CASE_STATUS_CHANGED = "CASE_STATUS_CHANGED"
    AI_INVESTIGATION_STARTED = "AI_INVESTIGATION_STARTED"
    AI_INVESTIGATION_COMPLETED = "AI_INVESTIGATION_COMPLETED"
    AI_INVESTIGATION_FAILED = "AI_INVESTIGATION_FAILED"
    AGENT_EXECUTION_STARTED = "AGENT_EXECUTION_STARTED"
    AGENT_EXECUTION_COMPLETED = "AGENT_EXECUTION_COMPLETED"
    AGENT_EXECUTION_FAILED = "AGENT_EXECUTION_FAILED"
    RAG_RETRIEVAL_STARTED = "RAG_RETRIEVAL_STARTED"
    RAG_RETRIEVAL_COMPLETED = "RAG_RETRIEVAL_COMPLETED"
    RAG_RETRIEVAL_FAILED = "RAG_RETRIEVAL_FAILED"
    PENDING_HUMAN_REVIEW_SET = "PENDING_HUMAN_REVIEW_SET"
    HUMAN_DECISION_SUBMITTED = "HUMAN_DECISION_SUBMITTED"
    HUMAN_OVERRIDE_DETECTED = "HUMAN_OVERRIDE_DETECTED"
    CASE_CLOSED = "CASE_CLOSED"
    API_ERROR = "API_ERROR"
    SECURITY_EVENT = "SECURITY_EVENT"
    AI_PROVIDER_SELECTED = "AI_PROVIDER_SELECTED"
    LLM_CALL_STARTED = "LLM_CALL_STARTED"
    LLM_CALL_COMPLETED = "LLM_CALL_COMPLETED"
    LLM_CALL_FAILED = "LLM_CALL_FAILED"
    LLM_OUTPUT_VALIDATION_FAILED = "LLM_OUTPUT_VALIDATION_FAILED"
    PROMPT_INJECTION_DETECTED = "PROMPT_INJECTION_DETECTED"
    PII_REDACTION_APPLIED = "PII_REDACTION_APPLIED"
    GUARDRAIL_VIOLATION_DETECTED = "GUARDRAIL_VIOLATION_DETECTED"
    ALERT_CREATED = "ALERT_CREATED"
    ALERT_RESOLVED = "ALERT_RESOLVED"
    INCIDENT_CREATED = "INCIDENT_CREATED"
    INCIDENT_STATUS_CHANGED = "INCIDENT_STATUS_CHANGED"
    INCIDENT_ASSIGNED = "INCIDENT_ASSIGNED"
    INCIDENT_CLOSED = "INCIDENT_CLOSED"
    NOTIFICATION_SENT = "NOTIFICATION_SENT"
    NOTIFICATION_FAILED = "NOTIFICATION_FAILED"
    NOTIFICATION_CREATED = "NOTIFICATION_CREATED"
    NOTIFICATION_READ = "NOTIFICATION_READ"
    NOTIFICATION_ARCHIVED = "NOTIFICATION_ARCHIVED"
    NOTIFICATION_PREFERENCES_UPDATED = "NOTIFICATION_PREFERENCES_UPDATED"
    NOTIFICATION_TEST_SENT = "NOTIFICATION_TEST_SENT"
    ADMIN_CONFIG_VIEWED = "ADMIN_CONFIG_VIEWED"
    ADMIN_CONFIG_UPDATED = "ADMIN_CONFIG_UPDATED"
    ADMIN_CONFIG_RESET = "ADMIN_CONFIG_RESET"
    FEATURE_FLAG_UPDATED = "FEATURE_FLAG_UPDATED"
    CONFIG_VALIDATION_FAILED = "CONFIG_VALIDATION_FAILED"
    CASE_ASSIGNED = "CASE_ASSIGNED"
    CASE_REASSIGNED = "CASE_REASSIGNED"
    CASE_ACCEPTED = "CASE_ACCEPTED"
    CASE_RELEASED = "CASE_RELEASED"
    CASE_TRANSFERRED = "CASE_TRANSFERRED"
    ASSIGNMENT_SLA_UPDATED = "ASSIGNMENT_SLA_UPDATED"
    ASSIGNMENT_PERMISSION_DENIED = "ASSIGNMENT_PERMISSION_DENIED"
    AI_FEEDBACK_SUBMITTED = "AI_FEEDBACK_SUBMITTED"
    AI_FEEDBACK_DISPOSITION_UPDATED = "AI_FEEDBACK_DISPOSITION_UPDATED"
    AI_FEEDBACK_BACKLOG_CREATED = "AI_FEEDBACK_BACKLOG_CREATED"
    AI_FEEDBACK_EXPORTED_TO_EVAL = "AI_FEEDBACK_EXPORTED_TO_EVAL"
    AI_FEEDBACK_CRITICAL_ISSUE_REPORTED = "AI_FEEDBACK_CRITICAL_ISSUE_REPORTED"
    SECURITY_CONFIG_VIEWED = "SECURITY_CONFIG_VIEWED"
    SECRET_PROVIDER_INITIALIZED = "SECRET_PROVIDER_INITIALIZED"
    KEY_VAULT_SECRET_LOADED = "KEY_VAULT_SECRET_LOADED"
    KEY_VAULT_SECRET_LOAD_FAILED = "KEY_VAULT_SECRET_LOAD_FAILED"
    MANAGED_IDENTITY_USED = "MANAGED_IDENTITY_USED"
    SECURITY_HEALTH_CHECK_EXECUTED = "SECURITY_HEALTH_CHECK_EXECUTED"
    RETENTION_POLICY_VIEWED = "RETENTION_POLICY_VIEWED"
    RETENTION_POLICY_UPDATED = "RETENTION_POLICY_UPDATED"
    RETENTION_SCAN_STARTED = "RETENTION_SCAN_STARTED"
    RETENTION_SCAN_COMPLETED = "RETENTION_SCAN_COMPLETED"
    RETENTION_ARCHIVE_DRY_RUN = "RETENTION_ARCHIVE_DRY_RUN"
    RETENTION_ARCHIVE_EXECUTED = "RETENTION_ARCHIVE_EXECUTED"
    RETENTION_PURGE_DRY_RUN = "RETENTION_PURGE_DRY_RUN"
    RETENTION_PURGE_EXECUTED = "RETENTION_PURGE_EXECUTED"
    RETENTION_PURGE_BLOCKED_LEGAL_HOLD = "RETENTION_PURGE_BLOCKED_LEGAL_HOLD"
    LEGAL_HOLD_CREATED = "LEGAL_HOLD_CREATED"
    LEGAL_HOLD_RELEASED = "LEGAL_HOLD_RELEASED"
    COMPLIANCE_EXPORT_REQUESTED = "COMPLIANCE_EXPORT_REQUESTED"
    COMPLIANCE_EXPORT_COMPLETED = "COMPLIANCE_EXPORT_COMPLETED"
    COMPLIANCE_EXPORT_FAILED = "COMPLIANCE_EXPORT_FAILED"
    READINESS_ASSESSMENT_STARTED = "READINESS_ASSESSMENT_STARTED"
    READINESS_ASSESSMENT_COMPLETED = "READINESS_ASSESSMENT_COMPLETED"
    READINESS_ASSESSMENT_FAILED = "READINESS_ASSESSMENT_FAILED"
    READINESS_EVIDENCE_ADDED = "READINESS_EVIDENCE_ADDED"
    READINESS_REPORT_EXPORTED = "READINESS_REPORT_EXPORTED"
    READINESS_RISK_CREATED = "READINESS_RISK_CREATED"
    READINESS_RISK_UPDATED = "READINESS_RISK_UPDATED"
    READINESS_RISK_CLOSED = "READINESS_RISK_CLOSED"
    GO_LIVE_DECISION_GENERATED = "GO_LIVE_DECISION_GENERATED"


AUDIT_EVENT_CATEGORY_BY_TYPE: dict[AuditEventType, str] = {
    AuditEventType.CASE_CREATED: "CASE",
    AuditEventType.CASE_VIEWED: "CASE",
    AuditEventType.CASE_STATUS_CHANGED: "CASE",
    AuditEventType.PENDING_HUMAN_REVIEW_SET: "CASE",
    AuditEventType.CASE_CLOSED: "CASE",
    AuditEventType.AI_INVESTIGATION_STARTED: "AI",
    AuditEventType.AI_INVESTIGATION_COMPLETED: "AI",
    AuditEventType.AI_INVESTIGATION_FAILED: "AI",
    AuditEventType.AGENT_EXECUTION_STARTED: "AGENT",
    AuditEventType.AGENT_EXECUTION_COMPLETED: "AGENT",
    AuditEventType.AGENT_EXECUTION_FAILED: "AGENT",
    AuditEventType.RAG_RETRIEVAL_STARTED: "RAG",
    AuditEventType.RAG_RETRIEVAL_COMPLETED: "RAG",
    AuditEventType.RAG_RETRIEVAL_FAILED: "RAG",
    AuditEventType.HUMAN_DECISION_SUBMITTED: "HUMAN_REVIEW",
    AuditEventType.HUMAN_OVERRIDE_DETECTED: "HUMAN_REVIEW",
    AuditEventType.API_ERROR: "ERROR",
    AuditEventType.SECURITY_EVENT: "SECURITY",
    AuditEventType.AI_PROVIDER_SELECTED: "AI",
    AuditEventType.LLM_CALL_STARTED: "AI",
    AuditEventType.LLM_CALL_COMPLETED: "AI",
    AuditEventType.LLM_CALL_FAILED: "AI",
    AuditEventType.LLM_OUTPUT_VALIDATION_FAILED: "AI",
    AuditEventType.PROMPT_INJECTION_DETECTED: "SECURITY",
    AuditEventType.PII_REDACTION_APPLIED: "SECURITY",
    AuditEventType.GUARDRAIL_VIOLATION_DETECTED: "AI",
    AuditEventType.ALERT_CREATED: "ALERTING",
    AuditEventType.ALERT_RESOLVED: "ALERTING",
    AuditEventType.INCIDENT_CREATED: "INCIDENT",
    AuditEventType.INCIDENT_STATUS_CHANGED: "INCIDENT",
    AuditEventType.INCIDENT_ASSIGNED: "INCIDENT",
    AuditEventType.INCIDENT_CLOSED: "INCIDENT",
    AuditEventType.NOTIFICATION_CREATED: "NOTIFICATION",
    AuditEventType.NOTIFICATION_SENT: "NOTIFICATION",
    AuditEventType.NOTIFICATION_FAILED: "NOTIFICATION",
    AuditEventType.NOTIFICATION_READ: "NOTIFICATION",
    AuditEventType.NOTIFICATION_ARCHIVED: "NOTIFICATION",
    AuditEventType.NOTIFICATION_PREFERENCES_UPDATED: "NOTIFICATION",
    AuditEventType.NOTIFICATION_TEST_SENT: "NOTIFICATION",
    AuditEventType.ADMIN_CONFIG_VIEWED: "ADMIN_CONFIG",
    AuditEventType.ADMIN_CONFIG_UPDATED: "ADMIN_CONFIG",
    AuditEventType.ADMIN_CONFIG_RESET: "ADMIN_CONFIG",
    AuditEventType.FEATURE_FLAG_UPDATED: "ADMIN_CONFIG",
    AuditEventType.CONFIG_VALIDATION_FAILED: "ADMIN_CONFIG",
    AuditEventType.CASE_ASSIGNED: "ASSIGNMENT",
    AuditEventType.CASE_REASSIGNED: "ASSIGNMENT",
    AuditEventType.CASE_ACCEPTED: "ASSIGNMENT",
    AuditEventType.CASE_RELEASED: "ASSIGNMENT",
    AuditEventType.CASE_TRANSFERRED: "ASSIGNMENT",
    AuditEventType.ASSIGNMENT_SLA_UPDATED: "ASSIGNMENT",
    AuditEventType.ASSIGNMENT_PERMISSION_DENIED: "ASSIGNMENT",
    AuditEventType.AI_FEEDBACK_SUBMITTED: "AI_FEEDBACK",
    AuditEventType.AI_FEEDBACK_DISPOSITION_UPDATED: "AI_FEEDBACK",
    AuditEventType.AI_FEEDBACK_BACKLOG_CREATED: "AI_FEEDBACK",
    AuditEventType.AI_FEEDBACK_EXPORTED_TO_EVAL: "AI_FEEDBACK",
    AuditEventType.AI_FEEDBACK_CRITICAL_ISSUE_REPORTED: "AI_FEEDBACK",
    AuditEventType.SECURITY_CONFIG_VIEWED: "SECURITY",
    AuditEventType.SECRET_PROVIDER_INITIALIZED: "SECURITY",
    AuditEventType.KEY_VAULT_SECRET_LOADED: "SECURITY",
    AuditEventType.KEY_VAULT_SECRET_LOAD_FAILED: "SECURITY",
    AuditEventType.MANAGED_IDENTITY_USED: "SECURITY",
    AuditEventType.SECURITY_HEALTH_CHECK_EXECUTED: "SECURITY",
    AuditEventType.RETENTION_POLICY_VIEWED: "COMPLIANCE",
    AuditEventType.RETENTION_POLICY_UPDATED: "COMPLIANCE",
    AuditEventType.RETENTION_SCAN_STARTED: "COMPLIANCE",
    AuditEventType.RETENTION_SCAN_COMPLETED: "COMPLIANCE",
    AuditEventType.RETENTION_ARCHIVE_DRY_RUN: "COMPLIANCE",
    AuditEventType.RETENTION_ARCHIVE_EXECUTED: "COMPLIANCE",
    AuditEventType.RETENTION_PURGE_DRY_RUN: "COMPLIANCE",
    AuditEventType.RETENTION_PURGE_EXECUTED: "COMPLIANCE",
    AuditEventType.RETENTION_PURGE_BLOCKED_LEGAL_HOLD: "COMPLIANCE",
    AuditEventType.LEGAL_HOLD_CREATED: "COMPLIANCE",
    AuditEventType.LEGAL_HOLD_RELEASED: "COMPLIANCE",
    AuditEventType.COMPLIANCE_EXPORT_REQUESTED: "COMPLIANCE",
    AuditEventType.COMPLIANCE_EXPORT_COMPLETED: "COMPLIANCE",
    AuditEventType.COMPLIANCE_EXPORT_FAILED: "COMPLIANCE",
    AuditEventType.READINESS_ASSESSMENT_STARTED: "READINESS",
    AuditEventType.READINESS_ASSESSMENT_COMPLETED: "READINESS",
    AuditEventType.READINESS_ASSESSMENT_FAILED: "READINESS",
    AuditEventType.READINESS_EVIDENCE_ADDED: "READINESS",
    AuditEventType.READINESS_REPORT_EXPORTED: "READINESS",
    AuditEventType.READINESS_RISK_CREATED: "READINESS",
    AuditEventType.READINESS_RISK_UPDATED: "READINESS",
    AuditEventType.READINESS_RISK_CLOSED: "READINESS",
    AuditEventType.GO_LIVE_DECISION_GENERATED: "READINESS",
}


ALLOWED_STATUS_TRANSITIONS: dict[CaseStatus, set[CaseStatus]] = {
    CaseStatus.NEW: {CaseStatus.AI_INVESTIGATION_IN_PROGRESS},
    CaseStatus.AI_INVESTIGATION_IN_PROGRESS: {CaseStatus.AI_INVESTIGATION_COMPLETED},
    CaseStatus.AI_INVESTIGATION_COMPLETED: {CaseStatus.PENDING_HUMAN_REVIEW},
    CaseStatus.PENDING_HUMAN_REVIEW: {
        CaseStatus.APPROVED,
        CaseStatus.HELD,
        CaseStatus.ESCALATED,
        CaseStatus.REJECTED,
    },
    CaseStatus.APPROVED: {CaseStatus.CLOSED},
    CaseStatus.HELD: {CaseStatus.CLOSED},
    CaseStatus.ESCALATED: {CaseStatus.CLOSED},
    CaseStatus.REJECTED: {CaseStatus.CLOSED},
    CaseStatus.CLOSED: set(),
}


DECISION_TO_STATUS: dict[ReviewDecision, CaseStatus] = {
    ReviewDecision.APPROVE: CaseStatus.APPROVED,
    ReviewDecision.HOLD: CaseStatus.HELD,
    ReviewDecision.ESCALATE: CaseStatus.ESCALATED,
    ReviewDecision.REJECT: CaseStatus.REJECTED,
}


ALLOWED_INCIDENT_STATUS_TRANSITIONS: dict[IncidentStatus, set[IncidentStatus]] = {
    IncidentStatus.OPEN: {IncidentStatus.ACKNOWLEDGED, IncidentStatus.INVESTIGATING, IncidentStatus.RESOLVED},
    IncidentStatus.ACKNOWLEDGED: {IncidentStatus.INVESTIGATING, IncidentStatus.RESOLVED},
    IncidentStatus.INVESTIGATING: {IncidentStatus.MITIGATED, IncidentStatus.RESOLVED},
    IncidentStatus.MITIGATED: {IncidentStatus.RESOLVED},
    IncidentStatus.RESOLVED: {IncidentStatus.CLOSED},
    IncidentStatus.CLOSED: set(),
}
